trigger:
 branches:
   include:
     - main
 paths:
   include:
     - src/Web/*

pool:
  name: self-hosted-pool

stages:
  - stage: Test
    jobs:
      - job: Dir
        steps:
          - checkout: self
          - script: dir
